//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.WebSites.JMR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mictlanix.WebSites.JMR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Usuario.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo de Asfalto.
        /// </summary>
        public static string AsphaltEquipment {
            get {
                return ResourceManager.GetString("AsphaltEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retroexcavadoras.
        /// </summary>
        public static string Backhoes {
            get {
                return ResourceManager.GetString("Backhoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar al Listado.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE.
        /// </summary>
        public static string CASE {
            get {
                return ResourceManager.GetString("CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAT.
        /// </summary>
        public static string CAT {
            get {
                return ResourceManager.GetString("CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grúas.
        /// </summary>
        public static string Cranes {
            get {
                return ResourceManager.GetString("Cranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cear Nuevo.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Alta.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Contraseña.
        /// </summary>
        public static string DisplayName_ChangePassword {
            get {
                return ResourceManager.GetString("DisplayName_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string DisplayName_LogOn {
            get {
                return ResourceManager.GetString("DisplayName_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Usuario.
        /// </summary>
        public static string DisplayName_Register {
            get {
                return ResourceManager.GetString("DisplayName_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Usuarios.
        /// </summary>
        public static string DisplayName_Users {
            get {
                return ResourceManager.GetString("DisplayName_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavadoras.
        /// </summary>
        public static string Excavators {
            get {
                return ResourceManager.GetString("Excavators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargadores Frontales.
        /// </summary>
        public static string FrontLoaders {
            get {
                return ResourceManager.GetString("FrontLoaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        public static string JCB {
            get {
                return ResourceManager.GetString("JCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Deere.
        /// </summary>
        public static string JohnDeere {
            get {
                return ResourceManager.GetString("JohnDeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komat&apos;su.
        /// </summary>
        public static string Komatsu {
            get {
                return ResourceManager.GetString("Komatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de contraseña no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_ChangePasswordFail {
            get {
                return ResourceManager.GetString("Message_ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña se ha cambiado exitosamente..
        /// </summary>
        public static string Message_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Message_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta o la contraseña nueva es inválida..
        /// </summary>
        public static string Message_ChangePasswordWrong {
            get {
                return ResourceManager.GetString("Message_ChangePasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de borrar esto?.
        /// </summary>
        public static string Message_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar el elemento porque existen dependencias en el sistema hacia él..
        /// </summary>
        public static string Message_DeleteUnsuccessful {
            get {
                return ResourceManager.GetString("Message_DeleteUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o contraseña es  incorrecto..
        /// </summary>
        public static string Message_InvalidUserPassword {
            get {
                return ResourceManager.GetString("Message_InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese su usuario y contraseña. O si usted no tiene un usuario, favor de.
        /// </summary>
        public static string Message_LoginRegister {
            get {
                return ResourceManager.GetString("Message_LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El inicio de sesión no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_LoginUnsuccessful {
            get {
                return ResourceManager.GetString("Message_LoginUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue exitoso. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string Message_RegisterUnsuccessful {
            get {
                return ResourceManager.GetString("Message_RegisterUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido. Por favor, verifica tus datos y vuelve a intentarlo. Si el problema persiste contacte a su administrador de sistema..
        /// </summary>
        public static string Message_UnknownError {
            get {
                return ResourceManager.GetString("Message_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe..
        /// </summary>
        public static string Message_UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("Message_UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motoconformadoras.
        /// </summary>
        public static string MotorGraders {
            get {
                return ResourceManager.GetString("MotorGraders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Nueva.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordarme?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Foto.
        /// </summary>
        public static string SavePhoto {
            get {
                return ResourceManager.GetString("SavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Serie.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string Title_LogOn {
            get {
                return ResourceManager.GetString("Title_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Title_Users {
            get {
                return ResourceManager.GetString("Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractores.
        /// </summary>
        public static string Tractors {
            get {
                return ResourceManager.GetString("Tractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir Foto.
        /// </summary>
        public static string UpdateFoto {
            get {
                return ResourceManager.GetString("UpdateFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} contiene un valor duplicado..
        /// </summary>
        public static string Validation_Duplicate {
            get {
                return ResourceManager.GetString("Validation_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo introducido no corresponde a un {0}..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o contraseña son invalidos..
        /// </summary>
        public static string Validation_InvalidLogOn {
            get {
                return ResourceManager.GetString("Validation_InvalidLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es inválida..
        /// </summary>
        public static string Validation_InvalidPassword {
            get {
                return ResourceManager.GetString("Validation_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña y la confirmación no coinciden..
        /// </summary>
        public static string Validation_PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener entre {2} y {1} caracteres de largo..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibro Compactadoras.
        /// </summary>
        public static string VibroCompactors {
            get {
                return ResourceManager.GetString("VibroCompactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volvo.
        /// </summary>
        public static string Volvo {
            get {
                return ResourceManager.GetString("Volvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
